# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image_worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12image_worker.proto\x12\x0bimageworker\"\x0f\n\rHealthRequest\"3\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tnode_name\x18\x02 \x01(\t\"B\n\x0eTransformation\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x13\n\x0bparams_json\x18\x02 \x01(\t\x12\r\n\x05order\x18\x03 \x01(\r\"y\n\tImageTask\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x12\n\ninput_path\x18\x02 \x01(\t\x12\x15\n\routput_format\x18\x03 \x01(\t\x12/\n\ntransforms\x18\x04 \x03(\x0b\x32\x1b.imageworker.Transformation\"H\n\nJobRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12&\n\x06images\x18\x02 \x03(\x0b\x32\x16.imageworker.ImageTask\"\x1a\n\x06JobAck\x12\x10\n\x08received\x18\x01 \x01(\t2\x8b\x01\n\x0bImageWorker\x12\x41\n\x06Health\x12\x1a.imageworker.HealthRequest\x1a\x1b.imageworker.HealthResponse\x12\x39\n\tSubmitJob\x12\x17.imageworker.JobRequest\x1a\x13.imageworker.JobAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=35
  _globals['_HEALTHREQUEST']._serialized_end=50
  _globals['_HEALTHRESPONSE']._serialized_start=52
  _globals['_HEALTHRESPONSE']._serialized_end=103
  _globals['_TRANSFORMATION']._serialized_start=105
  _globals['_TRANSFORMATION']._serialized_end=171
  _globals['_IMAGETASK']._serialized_start=173
  _globals['_IMAGETASK']._serialized_end=294
  _globals['_JOBREQUEST']._serialized_start=296
  _globals['_JOBREQUEST']._serialized_end=368
  _globals['_JOBACK']._serialized_start=370
  _globals['_JOBACK']._serialized_end=396
  _globals['_IMAGEWORKER']._serialized_start=399
  _globals['_IMAGEWORKER']._serialized_end=538
# @@protoc_insertion_point(module_scope)
